blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "blog"

urlpatterns = [
    path('', views.home, name='blog-home'),
    path('featured/', views.featured, name='blog-featured'),
    
    path('blog/<int:id>/', views.show, name='blog-show'),
    path('blog/create/', views.create, name='blog-create'),
    path('blog/<int:id>/update/', views.update, name='blog-update'),
    path('blog/<int:post_id>/comment/<int:comment_id>/update/', views.update_comment, name='update-comment'),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static
from users.forms import SigninForm


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('', include('blog.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html', authentication_form=SigninForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=100)
    content=models.TextField()
    date_posted=models.DateTimeField(default=timezone.now)
    author=models.ForeignKey(User, on_delete=models.CASCADE)
    is_featured=models.BooleanField("IS FEATURED", default=False)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post=models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    comment_user=models.ForeignKey(User, on_delete=models.CASCADE)
    body=models.TextField(max_length=200)

    def __str__(self):
        return "Comment for {}".format(self.post.title)

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Post, Comment

class BlogCreateForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=['title', 'content', 'is_featured']
        labels = {'content': 'Body', 'is_featured': 'Is Featured'}
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'add your title here', 'class': 'form-control'}),
            'content': forms.Textarea(attrs={'rows': 3, 'placeholder': 'add your content here', 'class': 'form-control'}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['body']
        labels = {'body': ''}
        widgets = {
            'body': forms.Textarea(attrs={'rows': 3, 'placeholder': 'add your comments here'}),
        }

blog/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Post, Comment
from .forms import BlogCreateForm, CommentForm
from .documents import PostDocument
from elasticsearch_dsl.query import MultiMatch
from .tasks import post_count

def home(request):
    post_count.delay()
    
    featured_posts = Post.objects.filter(is_featured=True)[:5]
    
    if 'q' in request.GET:
        q = request.GET['q']
        query = MultiMatch(query=q, fields=["title", "content"], fuzziness="AUTO")
        posts = PostDocument.search().query(query).to_queryset()
    else:
        posts = Post.objects.all().order_by('-id')
    context = {
        'posts': posts
    }

    context = {
        'posts': posts, 'featured_posts': featured_posts
    }
    return render(request, 'blog/home.html',context)

def featured(request):
    featured_posts = Post.objects.filter(is_featured=True)
    context={'featured_posts': featured_posts}
    return render(request, 'blog/featured.html', context)
    
def show(request,id):
    post = Post.objects.get(id=id)
    related_posts = Post.objects.all().exclude(id=id)[:3]
    
    comments = post.comments.all().order_by('-id')
    if request.method == "POST" and request.user.is_authenticated:
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment_form.instance.comment_user=request.user
            comment_form.instance.post=post
            comment_form.save()
            return redirect('/')
    else:
        comment_form = CommentForm()    
    context={'comment_form': comment_form, 'comments': comments, 'post': post, 'related_posts': related_posts}
    return render(request, 'blog/show.html', context)

@login_required
def create(request):
    if request.method == "POST":
        form = BlogCreateForm(request.POST)
        if form.is_valid():
            form.instance.author=request.user
            form.save()
            return redirect('/')
    else:
        form = BlogCreateForm()    
    context = {'form': form}
    return render(request, 'blog/create.html', context)

@login_required
def update(request, id):
    post = Post.objects.get(id=id)
    if not post.author == request.user:
        return redirect('/')
        
    if request.method == "POST":
        form = BlogCreateForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = BlogCreateForm(instance=post)
    context={'post': post, 'form': form}
    return render(request, 'blog/update.html', context)

@login_required
def update_comment(request,post_id, comment_id):
    post=Post.objects.get(id=post_id)
    comment = Comment.objects.get(id=comment_id)
    if not comment.comment_user == request.user:
        return redirect('/')
        
    if request.method == "POST":
        comment_form = CommentForm(request.POST, instance=comment)
        if comment_form.is_valid():
            comment_form.save()
            return redirect('blog:blog-show', post.id)
    else:
        comment_form = CommentForm(instance=comment)    
    context={'comment_form': comment_form, 'comment': comment, 'post': post}
    return render(request, 'blog/update_comment.html', context)


def search(request,q):
    q = request.GET.get("q")
    context={}
    if q:
        s = PostDocument.search().query("match", title=q)
        context["posts"] = s
    return render(request, "blog/search.html")

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% block content %}
    <h1>This is an about page</h1>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>


    {% if title %}
        <title>Django Blog - {{ title }}</title>
    {% else %}
        <title>Django Blog</title>
    {% endif %}
</head>
<body>
  <header class="site-header">
      <nav class="navbar navbar-expand-sm bg-light">
          <div class="container-fluid">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:blog-home' %}">Home</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'profile' %}">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:blog-create' %}">Create Blog</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
                {% endif %}
            </ul>
            <form class="d-flex" action="{% url 'blog:blog-home' %}" method="get">
              <input name="q" type="text"class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </nav>
  </header>
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        {% block content %}{% endblock %}
      </div>
      <div class="col-md-4">
        <div >
          {% block content1 %}{% endblock %}
        </div>

        <div >
          {% block content2 %}{% endblock %}
          
        </div>

      </div>

      
    </div>
  </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/create.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container mt-3">
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-dark">Create Post</button>
    </form>
</div>
{% endblock content %}

blog/templates/blog/featured.html
{% extends 'blog/base.html' %}
{% load static %}
{% load breakpoint %}
{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/home.css' %}">
    <h3 class="text-center">All Featured Blogs</h3>
    <hr>
    {% for post in featured_posts %}
      <div class="row">
      <div class="col-md-6">
          <!-- <img src="{{post.author.profile.image.url}}" alt="" class="img-thumbnail" style="max-height: 50px; max-width: 50px;"> -->
          <a class="mr-2 post-title" href="{% url 'blog:blog-show' post.id %}">{{ post.title }}</a>
          <p>{{ post.content }}</p>
          
      </div>
      <div class="col-md-2">
          <p class="text-end">Author:{{post.author.username}}</p>
          <p class="text-end">{{post.comments.count}}Comments</p>
      </div>
    </div>
    <hr>
    {% endfor %}

{% endblock content %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}
{% load breakpoint %}
{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/home.css' %}">
    <h3 class="text-center">All Blogs</h3>
    <hr>
    {% for post in posts %}
      <div class="row">
      <div class="col-md-6">
          <!-- <img src="{{post.author.profile.image.url}}" alt="" class="img-thumbnail" style="max-height: 50px; max-width: 50px;"> -->
          <a class="mr-2 post-title" href="{% url 'blog:blog-show' post.id %}">{{ post.title }}</a>
          <p>{{ post.content }}</p>
          
      </div>
      <div class="col-md-2">
          <p class="text-end">Author:{{post.author.username}}</p>
          <p class="text-end">{{post.comments.count}}Comments</p>
      </div>
    </div>
    <hr>
    {% endfor %}

{% endblock content %}


{% block content1 %}
<a href="{% url 'blog:blog-featured' %}"><h3 class="text-center post-title">Featured Blogs</h3></a>
  <ul class="list-group">
    {% for post in featured_posts %}
    <li class="list-group-item list-group-item-light">
      <p>Posted By: {{post.author.username}}</p>
      <a class="mr-2 post-title" href="{% url 'blog:blog-show' post.id %}">{{ post.title }}</a>
      <p>{{ post.content }}</p>
    </li>
    <br>
    {% endfor %}
  </ul>
{% endblock content1 %}

blog/templates/blog/show.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">

    <h1 class="text-center">{{post.title}}</h1>
    <p>{{post.content}}</p>
    <small>Posted By {{post.author}}</small> <br>
    <small>Posted On {{post.date_posted}}</small><br><br>
   

    <form action="" method="POST">
        {% csrf_token %}
        {{comment_form.as_p}}
        <button type="submit" class="btn btn-dark btn-sm">Add a Comment</button>
    </form>
    
    {% for comment in comments %}
        <ul>
            {% if comment.comment_user == request.user %}
                <a href="{% url 'blog:update-comment' post.id comment.id %}"><li>{{comment.body}}</li></a>
            {% endif %}
        </ul>
    {% endfor %}
{% endblock content %}

{% block content2 %}
    <h3>Related Blogs</h3>
    <ul class="list-group">
        {% for post in related_posts %}
        <li class="list-group-item list-group-item-light">
          <p>Posted By: {{post.author.username}}</p>
          <a class="mr-2 post-title" href="{% url 'blog:blog-show' post.id %}">{{ post.title }}</a>
          <p>{{ post.content }}</p>
        </li>
        <br>
        {% endfor %}
      </ul>
{% endblock %}

blog/templates/blog/update.html
{% extends 'blog/base.html' %}
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Update Post</button>
</form>
{% endblock content %}

blog/templates/blog/update_comment.html
{% extends 'blog/base.html' %}
{% load breakpoint %}
{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {{comment_form.as_p}}
        <button type="submit">Update Comment</button>
    </form>
{% endblock content %}